### ISSUE TITLE
Mod Not Functioning?

### ISSUE THREAD

**Issue by MoonbeamMage** [misleadingname/tourneymod#2]
Apologies if this isn't the right way to do this!

I have the tourney mod downloaded but when I try to interact with the tourney area, it says the lobby host (me) doesn't have the mod. I have Weave as well, is there something else I'm missing?

Thank you,
Moonbeam

**Comment by misleadingname** [comment]
The webfishing updates broke the mod, will fix whenever I can work on tourneymod.

**Comment by MoonbeamMage** [comment]
Ah! No worries, thank you for the information!
